name: Release

# Триггер: запуск только при создании нового тега в формате v*.*.*
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    
    # Даем воркфлоу права на запись контента (создание релиза и загрузку файлов)
    permissions:
      contents: write
      
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 1: Создаем черновик релиза, чтобы получить URL для загрузки
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # Используем ref_name для получения чистого тега (например, v1.0.0)
          release_name: Release ${{ github.ref_name }}
          draft: true # <-- Очень важно: создаем как черновик
          prerelease: false

      # Шаг 2: Собираем и загружаем бинарники в цикле
      - name: Build and Upload Binaries
        run: |
          for GOOS in linux windows darwin; do
            for GOARCH in amd64 arm64; do
              # Пропускаем комбинации, которые не нужны или не существуют
              if [ "$GOOS" == "windows" ] && [ "$GOARCH" == "arm64" ]; then
                continue
              fi

              BINARY_NAME="roar-${GOOS}-${GOARCH}"
              if [ "$GOOS" == "windows" ]; then
                BINARY_NAME+=".exe"
              fi

              echo "Building for $GOOS/$GOARCH..."
              CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build -v -o build/${BINARY_NAME} ./cmd/roar/

              echo "Uploading ${BINARY_NAME} to release..."
              # Используем GitHub CLI для загрузки артефакта в созданный релиз
              gh release upload ${{ github.ref_name }} build/${BINARY_NAME} --clobber
            done
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Шаг 3: Публикуем релиз (убираем статус "draft")
      - name: Publish Release
        run: gh release edit ${{ github.ref_name }} --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}